### ISSUE TITLE
bug: undo/redo many times may cause "Uncaught RangeError: Array buffer allocation failed" error

### ISSUE THREAD

**Issue by AmyOrz** [Wonder-Technology/Wonder.js#18]
# environment
## version
v1.0.0-alpha.17.7

# description

# reason
deep copy buffer spend too much memory, it will cause browser fail

# solution
update engine version

**Comment by yyc-git** [comment]
github/Wonder-Technology/Wonder-Editor#10

#4

**Comment by yyc-git** [comment]
refer to [Wonder-Technology/Wonder-Editor#10](https://github.com/Wonder-Technology/Wonder-Editor/issues/10)

**Comment by yyc-git** [comment]
fixed in wonder.js->v1.0.0-alpha.18.3
